import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../domain/entities/crew/crew_entity.dart';

part 'crew_member_model.freezed.dart';
part 'crew_member_model.g.dart';

/// A Freezed union class representing a crew member.
///
/// This class provides a convenient way to create and manage crew member data,
/// including serialization from and to JSON, and conversion to domain entities.
@freezed
class CrewMember with _$CrewMember {
  /// The default factory constructor for creating a new [CrewMember] instance.
  ///
  /// Requires [crewId], [id], [image], [name], and [userId] to be provided.
  const factory CrewMember({
    required int crewId,
    required int id,
    required String image,
    required String name,
    required int userId,
  }) = _CrewMember;

  /// A factory constructor for creating a new [CrewMember] instance from a JSON map.
  ///
  /// Utilizes the `_$CrewMemberFromJson` function generated by the Freezed package
  /// to parse the JSON map into a [CrewMember] instance.
  factory CrewMember.fromJson(Map<String, dynamic> json) =>
      _$CrewMemberFromJson(json);

  /// Converts the [CrewMember] instance to a [CrewMemberEntity].
  ///
  /// This method is used to convert the Freezed data model to a domain entity,
  /// which represents the business logic of the application.
  CrewMemberEntity toEntity() {
    return CrewMemberEntity(
      crewId: crewId,
      id: id,
      image: image,
      name: name,
      userId: userId,
    );
  }
}

/// A Freezed union class representing a container for multiple crew members.
///
/// This class is used to group a list of [CrewMember] instances and associated message,
/// providing serialization and conversion to domain entities.
@freezed
class CrewMembersContainer with _$CrewMembersContainer {
  /// The default factory constructor for creating a new [CrewMembersContainer] instance.
  ///
  /// Requires a [message] and a list of [CrewMember] instances as [payload].
  const factory CrewMembersContainer({
    required String message,
    required List<CrewMember> payload,
  }) = _CrewMembersContainer;

  /// A factory constructor for creating a new [CrewMembersContainer] instance from a JSON map.
  ///
  /// Utilizes the `_$CrewMembersContainerFromJson` function generated by the Freezed package
  /// to parse the JSON map into a [CrewMembersContainer] instance.
  factory CrewMembersContainer.fromJson(Map<String, dynamic> json) =>
      _$CrewMembersContainerFromJson(json);

  /// Converts the [CrewMembersContainer] instance to a [CrewMembersContainerEntity].
  ///
  /// This method is used to convert the Freezed data model to a domain entity,
  /// which represents the business logic of the application.
  CrewMembersContainerEntity toEntity() {
    return CrewMembersContainerEntity(
      message: message,
      payload: payload.map((crewMember) => crewMember.toEntity()).toList(),
    );
  }
}
